### ISSUE TITLE
pep8 extension avec python3

### ISSUE THREAD

**Issue by dpinsard** [SiggyF/notebooks#1]
Hello,

When I use Python3 the following cell produce an error :

%%pep8
a=5

---

TypeError                                 Traceback (most recent call last)
<ipython-input-3-ade26fb101bd> in <module>()
----> 1 get_ipython().run_cell_magic('pep8', '', 'a=5')

/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2262             magic_arg_s = self.var_expand(line, stack_depth)
   2263             with self.builtin_trap:
-> 2264                 result = fn(magic_arg_s, cell)
   2265             return result
   2266 

/root/.ipython/extensions/pep8_magic.py in pep8(line, cell)
     38     with tempfile.NamedTemporaryFile() as f:
     39         # save to file
---> 40         f.write(cell + "\n")
     41         # make sure it's written
     42         f.flush()

/usr/lib/python3.4/tempfile.py in func_wrapper(_args, *_kwargs)
    536             @_functools.wraps(func)
    537             def func_wrapper(_args, *_kwargs):
--> 538                 return func(_args, *_kwargs)
    539             # Avoid closing the file as long as the wrapper is alive,
    540             # see issue #18879.

TypeError: 'str' does not support the buffer interface

Thanks for your help.

**Comment by SiggyF** [comment]
Thanks I'll have to look into that. Probably related to that I open the stdout as a BytesIO instead of a StringIO 
https://github.com/SiggyF/notebooks/blob/master/pep8_magic.py#L36

**Comment by SiggyF** [comment]
Or it might be related to that NamedTemporaryFiles are opened as binary by default. 
https://docs.python.org/3.5/library/tempfile.html#tempfile.NamedTemporaryFile
