### ISSUE TITLE
Permission Error when running pep8_magic in jupyter notebooks

### ISSUE THREAD

**Issue by mgserafi** [SiggyF/notebooks#3]
I'm trying to run `pep8_magic` in jupyter notebooks, following this [example](http://nbviewer.jupyter.org/github/SiggyF/notebooks/blob/master/styleguide.ipynb).  However, when I have `%%pep8` in a cell, I get a Permission error:

`INFO:pep8: ...\AppData\Local\Temp\tmp67jjo44b:1:1: E902 PermissionError: [Errno 13] Permission denied: '...\\AppData\\Local\\Temp\\tmp67jjo44b'`

I'm currently using Jupyter 4.1.0 and ipython 5.1.0

**Comment by SiggyF** [comment]
I use a NamedTemporaryFile, which is opened twice (once written to, then checked). This is not supported under windows. 
See https://docs.python.org/3.5/library/tempfile.html#tempfile.NamedTemporaryFile and https://stackoverflow.com/q/23212435/386327 for details. 
I'm not sure how to work around this.
