### ISSUE TITLE
NameError: Decorator can only run in context where `get_ipython` exists

### ISSUE THREAD

**Issue by joshjacobson** [SiggyF/notebooks#4]
Trying to get pep8 magic working:

Traceback (most recent call last):
  File "D:\Downloads\pep8_magic.py", line 26, in <module>
    @register_cell_magic
  File "C:\Users\__\Anaconda3\lib\site-packages\IPython\core\magic.py", line 230, in magic_deco
    raise NameError('Decorator can only run in context where '
NameError: Decorator can only run in context where `get_ipython` exists

**Comment by SiggyF** [comment]
With the latest ipython you have to install using `jupyter nbextension install --user pep8_magic.py` the extension . I have updated the notebook accordingly. pep8_magic won't work under windows, see #3 .
